# # version: '3.8'

# services:
#   postgres:
#     image: postgres:latest
#     container_name: my_postgres
#     env_file: ./env/postgres.env
#     environment:
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_DB}
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - my_network


#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: my_pgadmin
#     env_file:
#       - ./env/pgadmin.env
#     ports:
#       - "5050:80"
#     depends_on:
#       - postgres
#     networks:
#       - my_network

# volumes:
#   postgres_data:

# networks:
#   my_network:
#     driver: bridge


# version: '3.8'

# services:
#   postgres:
#     image: postgres:latest
#     container_name: my_postgres
#     env_file:
#       - ./env/postgres.env
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - my_network

#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: my_pgadmin
#     env_file:
#       - ./env/pgadmin.env
#     ports:
#       - "5050:80"
#     depends_on:
#       - postgres
#     networks:
#       - my_network
#     volumes:
#       - ./pg_admin_server.json:/pgadmin4/servers.json:ro

#   backend:
#     build:
#       context: ../backend
#       dockerfile: ../docker/backend.dockerfile
#     container_name: my_backend
#     env_file:
#       - ./env/backend.env
#     ports:
#       - 3001:3000  
#     depends_on:
#       - postgres
#     networks:
#       - my_network

#   frontend:
#     build:
#       context: ../frontend
#       dockerfile: ../docker/frontend.dockerfile
#     container_name: my_frontend
#     env_file:
#       - ./env/frontend.env
#     ports:
#       - 8080:80 
#     depends_on:
#       - backend
#     networks:
#       - my_network

# volumes:
#   postgres_data: {}

# networks:
#   my_network:
#     driver: bridge

####### Version Traefik ####################
version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443" # https entrypoint
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure" # redirections vers HTTPS*-
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=admin@example.com"  
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443" # https port 
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt # certificate
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: my_postgres
    env_file:
      - ./env/postgres.env
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    env_file:
      - ./env/pgadmin.env
    volumes:
      - ./pg_admin_server.json:/pgadmin4/servers.json:ro
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.ipssi`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.routers.pgadmin.tls.certresolver=myresolver"

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.dockerfile
    container_name: my_backend
    env_file:
      - ./env/backend.env
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.ipssi`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.middlewares.cors.headers.accessControlAllowMethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accessControlAllowOrigin=http://app.ipssi"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=Content-Type,Authorization"
      - "traefik.http.middlewares.cors.headers.accessControlAllowCredentials=true"
      - "traefik.http.routers.backend.middlewares=cors"
      
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.dockerfile
    container_name: my_frontend
    env_file:
      - ./env/frontend.env
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.ipssi`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

networks:
  my_network:
    driver: bridge